# Generated by Django 6.0.1 on 2026-01-15 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='is_published',
        ),
    ]
