# Generated by Django 6.0.1 on 2026-01-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_remove_test_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
