# Generated by Django 6.0.1 on 2026-01-18 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_test_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.test'),
        ),
    ]
